name: build

on: push

jobs:
  build:

    name: my job
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: my first step
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Kenneth
          LAST_NAME: Rough
        run: echo $MY_VAR $FIRST_NAME $LAST_NAME
      - name: my second step
        if: success()
        run: echo "The previous step has finished succesfully"
      - name: my third step
        uses: actions/checkout@v1
        run: echo "The third step has finished"
      - name: my fourth step
        uses: actions/first-interaction@55b296e
        with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users'' first issue'
        pr-message: 'Message that will be displayed on users'' first pr'
        
          
